package org.powernukkitx.protocol.types;

public enum CommandRequestPacket_VersionEnum {
  INVALID,

  INITIAL,

  TPROTATIONCLAMPING,

  NEWBEDROCKCMDSYSTEM,

  EXECUTEUSESVEC3,

  CLONEFIXES,

  UPDATEAQUATIC,

  ENTITYSELECTORUSESVEC3,

  CONTAINERSDONTDROPITEMSANYMORE,

  FILTERSOBEYDIMENSIONS,

  EXECUTEANDBLOCKCOMMANDANDSELFSELECTORFIXES,

  INSTANTEFFECTSUSETICKS,

  DONTREGISTERBROKENFUNCTIONCOMMANDS,

  CLEARSPAWNPOINTCOMMAND,

  CLONEANDTELEPORTROTATIONFIXES,

  TELEPORTDIMENSIONFIXES,

  CLONEUPDATEBLOCKANDTIMEFIXES,

  CLONEINTERSECTFIX,

  FUNCTIONEXECUTEORDERANDCHESTSLOTFIX,

  NONTICKINGAREASNOLONGERCONSIDEREDLOADED,

  SPREADPLAYERSHAZARDANDRESOLVEPLAYERBYNAMEFIX,

  NEWEXECUTECOMMANDSYNTAXEXPERIMENTANDCHESTLOOTTABLEFIXANDTELEPORTFACINGVERTICALUNCLAMPEDANDLOCATEBIOMEANDFEATUREMERGED,

  WATERLOGGINGADDEDTOSTRUCTURECOMMAND,

  SELECTORDISTANCEFILTEREDANDRELATIVEROTATIONFIX,

  NEWSUMMONCOMMANDADDEDROTATIONOPTIONSANDBUBBLECOLUMNCLONEFIXANDEXECUTEINDIMENSIONTELEPORTFIXANDNEWEXECUTEROTATIONFIX,

  NEWEXECUTECOMMANDRELEASEENCHANTCOMMANDLEVELFIXANDHASITEMDATAFIXANDCOMMANDDEFERRAL,

  EXECUTEIFSCOREFIXES,

  REPLACEITEMANDLOOTREPLACEBLOCKCOMMANDSDONOTPLACEITEMSINTOCAULDRONSFIX,

  CHANGESTOCOMMANDORIGINROTATION,

  REMOVEAUXVALUEPARAMETERFROMBLOCKCOMMANDS,

  VOLUMESELECTORFIXES,

  ENABLESUMMONROTATION,

  SUMMONCOMMANDDEFAULTROTATION,

  POSITIONALDIMENSIONFILTERING,

  COMMANDSELECTORHASITEMFILTERNOLONGERCALLSSAMEITEMFUNCTION,

  AGENTSWEEPINGBLOCKTEST,

  BLOCKSTATEEQUALS,

  COMMANDPOSITIONFIX,

  COMMANDSELECTORHASITEMFILTERUSESDATAASDAMAGEFORSELECTINGDAMAGEABLEITEMS,

  EXECUTEDETECTCONDITIONSUBCOMMANDNOTALLOWNONLOADEDBLOCKS,

  REMOVESUICIDEKEYWORD,

  CLONECONTAINERBLOCKENTITYREMOVALFIX,

  STOPSOUNDMUSICFIX,

  SPREADPLAYERSSTUCKINGROUNDFIXANDMAXHEIGHTPARAMETER,

  LOCATESTRUCTUREOUTPUT,

  POSTBLOCKFLATTENING,

  TESTFORBLOCKCOMMANDDOESNOTIGNOREBLOCKSTATE,

  COUNT,

  LATEST;

  public static CommandRequestPacket_VersionEnum fromByte(int b) {
    return values()[b];
  }

  public int toByte() {
    return this.ordinal();
  }
}
