package org.powernukkitx.protocol.types;

public enum FullContainerName_Container_NameEnum {
  ANVILINPUTCONTAINER,

  ANVILMATERIALCONTAINER,

  ANVILRESULTPREVIEWCONTAINER,

  SMITHINGTABLEINPUTCONTAINER,

  SMITHINGTABLEMATERIALCONTAINER,

  SMITHINGTABLERESULTPREVIEWCONTAINER,

  ARMORCONTAINER,

  LEVELENTITYCONTAINER,

  BEACONPAYMENTCONTAINER,

  BREWINGSTANDINPUTCONTAINER,

  BREWINGSTANDRESULTCONTAINER,

  BREWINGSTANDFUELCONTAINER,

  COMBINEDHOTBARANDINVENTORYCONTAINER,

  CRAFTINGINPUTCONTAINER,

  CRAFTINGOUTPUTPREVIEWCONTAINER,

  RECIPECONSTRUCTIONCONTAINER,

  RECIPENATURECONTAINER,

  RECIPEITEMSCONTAINER,

  RECIPESEARCHCONTAINER,

  RECIPESEARCHBARCONTAINER,

  RECIPEEQUIPMENTCONTAINER,

  RECIPEBOOKCONTAINER,

  ENCHANTINGINPUTCONTAINER,

  ENCHANTINGMATERIALCONTAINER,

  FURNACEFUELCONTAINER,

  FURNACEINGREDIENTCONTAINER,

  FURNACERESULTCONTAINER,

  HORSEEQUIPCONTAINER,

  HOTBARCONTAINER,

  INVENTORYCONTAINER,

  SHULKERBOXCONTAINER,

  TRADEINGREDIENT1CONTAINER,

  TRADEINGREDIENT2CONTAINER,

  TRADERESULTPREVIEWCONTAINER,

  OFFHANDCONTAINER,

  COMPOUNDCREATORINPUT,

  COMPOUNDCREATOROUTPUTPREVIEW,

  ELEMENTCONSTRUCTOROUTPUTPREVIEW,

  MATERIALREDUCERINPUT,

  MATERIALREDUCEROUTPUT,

  LABTABLEINPUT,

  LOOMINPUTCONTAINER,

  LOOMDYECONTAINER,

  LOOMMATERIALCONTAINER,

  LOOMRESULTPREVIEWCONTAINER,

  BLASTFURNACEINGREDIENTCONTAINER,

  SMOKERINGREDIENTCONTAINER,

  TRADE2INGREDIENT1CONTAINER,

  TRADE2INGREDIENT2CONTAINER,

  TRADE2RESULTPREVIEWCONTAINER,

  GRINDSTONEINPUTCONTAINER,

  GRINDSTONEADDITIONALCONTAINER,

  GRINDSTONERESULTPREVIEWCONTAINER,

  STONECUTTERINPUTCONTAINER,

  STONECUTTERRESULTPREVIEWCONTAINER,

  CARTOGRAPHYINPUTCONTAINER,

  CARTOGRAPHYADDITIONALCONTAINER,

  CARTOGRAPHYRESULTPREVIEWCONTAINER,

  BARRELCONTAINER,

  CURSORCONTAINER,

  CREATEDOUTPUTCONTAINER,

  SMITHINGTABLETEMPLATECONTAINER,

  CRAFTERLEVELENTITYCONTAINER,

  DYNAMICCONTAINER;

  public static FullContainerName_Container_NameEnum fromByte(int b) {
    return values()[b];
  }

  public int toByte() {
    return this.ordinal();
  }
}
